name: Format Markdown 

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  format-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Prettier
        run: npm install -g prettier@3.8.4

      - name: Check Markdown formatting
        run: prettier --check "**/*.md"
